[package]
name = "gtfu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.5"
human-panic = "2.0.2"
log = "0.4.22"

[build-dependencies]
clap = { version = "4.5.23", features = ["derive"] }
clap_mangen = "0.2.24"
